services:
  php:
      build: .
      user: 1000:1000
      container_name: chess_website_php
      restart: always
      volumes:
          - ./:/usr/share/nginx/website
          - /usr/share/nginx/website/vendor
          - ./docker/php/8.3/cli/php.ini:/usr/local/etc/php/php.ini
      working_dir: /usr/share/nginx/website
  nginx:
      image: nginx:1.20
      container_name: chess_website_nginx
      ports:
          - "80:80"
          - "443:443"
      restart: always
      volumes:
          - ./:/usr/share/nginx/website
          - /usr/share/nginx/website/vendor
          - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
          - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./docker/nginx/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
          - ./docker/nginx/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem
      working_dir: /usr/share/nginx/website
