<?php

/**
 * Returns the importmap for this application.
 *
 * - "path" is a path inside the asset mapper system. Use the
 *     "debug:asset-map" command to see the full list of paths.
 *
 * - "entrypoint" (JavaScript only) set to true for any module that will
 *     be used as an "entrypoint" (and passed to the importmap() Twig function).
 *
 * The "importmap:require" command can be used to add new entries to this file.
 *
 * This file has been auto-generated by the importmap commands.
 */
return [
    'img/pieces/png/75/wKing' => [
        'path' => './assets/img/pieces/png/75/wKing.png',
    ],
    'img/pieces/png/75/wbKing' => [
        'path' => './assets/img/pieces/png/75/wbKing.png',
    ],
    'img/pieces/png/75/bKing' => [
        'path' => './assets/img/pieces/png/75/bKing.png',
    ],
    'app' => [
        'path' => './assets/app.js',
        'entrypoint' => true,
    ],
    'js/chessboard/classical' => [
        'path' => './assets/js/chessboard/classical/index.js',
        'entrypoint' => true,
    ],
    'js/chessboard/fischer_random' => [
        'path' => './assets/js/chessboard/fischer_random/index.js',
        'entrypoint' => true,
    ],
    'js/chessboard/san_movetext' => [
        'path' => './assets/js/chessboard/san_movetext/index.js',
        'entrypoint' => true,
    ],
    'js/chessboard/fen_string' => [
        'path' => './assets/js/chessboard/fen_string/index.js',
        'entrypoint' => true,
    ],
    'js/openings/index' => [
        'path' => './assets/js/openings/index/index.js',
        'entrypoint' => true,
    ],
    'js/play/computer' => [
        'path' => './assets/js/play/computer/index.js',
        'entrypoint' => true,
    ],
    'js/footer/about' => [
        'path' => './assets/js/footer/about/index.js',
        'entrypoint' => true,
    ],
    'cm-chessboard' => [
        'version' => '8.5.0',
    ],
    'cm-chessboard/src/extensions/accessibility/Accessibility' => [
        'version' => '8.5.0',
    ],
    'cm-chessboard/src/extensions/accessibility/I18n' => [
        'version' => '8.5.0',
    ],
    'cm-chessboard/src/extensions/arrows/Arrows' => [
        'version' => '8.5.0',
    ],
    'cm-chessboard/src/extensions/auto-border-none/AutoBorderNone' => [
        'version' => '8.5.0',
    ],
    'cm-chessboard/src/extensions/html-layer/HtmlLayer' => [
        'version' => '8.5.0',
    ],
    'cm-chessboard/src/extensions/markers/Markers' => [
        'version' => '8.5.0',
    ],
    'cm-chessboard/src/extensions/persistence/Persistence' => [
        'version' => '8.5.0',
    ],
    'cm-chessboard/src/extensions/promotion-dialog/PromotionDialog' => [
        'version' => '8.5.0',
    ],
    'cm-chessboard/src/lib/Svg' => [
        'version' => '8.5.0',
    ],
    'cm-chessboard/src/lib/Utils' => [
        'version' => '8.5.0',
    ],
    'cm-chessboard/src/model/ChessboardState' => [
        'version' => '8.5.0',
    ],
    'cm-chessboard/src/model/Extension' => [
        'version' => '8.5.0',
    ],
    'cm-chessboard/src/model/Position' => [
        'version' => '8.5.0',
    ],
    'cm-chessboard/src/view/ChessboardView' => [
        'version' => '8.5.0',
    ],
    'cm-chessboard/src/view/PositionAnimationsQueue' => [
        'version' => '8.5.0',
    ],
    'cm-chessboard/src/view/VisualMoveInput' => [
        'version' => '8.5.0',
    ],
    'bootstrap' => [
        'version' => '5.3.2',
    ],
    '@popperjs/core' => [
        'version' => '2.11.8',
    ],
    'bootstrap/dist/js/bootstrap.bundle.min.js' => [
        'version' => '5.3.2',
    ],
    'bootstrap/dist/css/bootstrap.min.css' => [
        'version' => '5.3.2',
        'type' => 'css',
    ],
    'bootstrap/js/dist/modal.js' => [
        'version' => '5.3.2',
    ],
    'bootstrap-icons/font/bootstrap-icons.min.css' => [
        'version' => '1.11.3',
        'type' => 'css',
    ],
    'jwt-decode' => [
        'version' => '4.0.0',
    ],
];
