<?php

/**
 * Returns the importmap for this application.
 *
 * - "path" is a path inside the asset mapper system. Use the
 *     "debug:asset-map" command to see the full list of paths.
 *
 * - "entrypoint" (JavaScript only) set to true for any module that will
 *     be used as an "entrypoint" (and passed to the importmap() Twig function).
 *
 * The "importmap:require" command can be used to add new entries to this file.
 *
 * This file has been auto-generated by the importmap commands.
 */
return [
    'js/pages/play/online/index.js' => [
        'path' => './assets/js/pages/play/online/index.js',
        'entrypoint' => true,
    ],
    'js/pages/play/computer/index.js' => [
        'path' => './assets/js/pages/play/computer/index.js',
        'entrypoint' => true,
    ],
    'js/pages/chessboard/classical/index.js' => [
        'path' => './assets/js/pages/chessboard/classical/index.js',
        'entrypoint' => true,
    ],
    'js/pages/chessboard/fischer_random/index.js' => [
        'path' => './assets/js/pages/chessboard/fischer_random/index.js',
        'entrypoint' => true,
    ],
    'js/pages/chessboard/rav_movetext/index.js' => [
        'path' => './assets/js/pages/chessboard/rav_movetext/index.js',
        'entrypoint' => true,
    ],
    'js/pages/chessboard/san_movetext/index.js' => [
        'path' => './assets/js/pages/chessboard/san_movetext/index.js',
        'entrypoint' => true,
    ],
    'js/pages/chessboard/fen_string/index.js' => [
        'path' => './assets/js/pages/chessboard/fen_string/index.js',
        'entrypoint' => true,
    ],
    'js/pages/openings/eco_code/index.js' => [
        'path' => './assets/js/pages/openings/eco_code/index.js',
        'entrypoint' => true,
    ],
    'js/pages/openings/name/index.js' => [
        'path' => './assets/js/pages/openings/name/index.js',
        'entrypoint' => true,
    ],
    'js/pages/openings/san_movetext/index.js' => [
        'path' => './assets/js/pages/openings/san_movetext/index.js',
        'entrypoint' => true,
    ],
    'js/pages/database/search_games/index.js' => [
        'path' => './assets/js/pages/database/search_games/index.js',
        'entrypoint' => true,
    ],
    'js/pages/database/annotated_games/index.js' => [
        'path' => './assets/js/pages/database/annotated_games/index.js',
        'entrypoint' => true,
    ],
    '@chesslablab/cmblab' => [
        'version' => '0.0.1',
    ],
    '@chesslablab/jsblab' => [
        'version' => '0.1.8',
    ],
    'bootstrap' => [
        'version' => '5.3.2',
    ],
    'bootstrap/dist/js/bootstrap.bundle.min.js' => [
        'version' => '5.3.2',
    ],
    'bootstrap/dist/css/bootstrap.min.css' => [
        'version' => '5.3.2',
        'type' => 'css',
    ],
    'bootstrap/js/dist/modal.js' => [
        'version' => '5.3.2',
    ],
    'jwt-decode' => [
        'version' => '4.0.0',
    ],
];
